//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibraryProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(JOURNAL.BOOK_ID) as Book_Count
        ///FROM CLIENTS
        ///LEFT JOIN JOURNAL
        ///    ON CLIENTS.ID = JOURNAL.CLIENT_ID
        ///WHERE CLIENTS.ID = :ID
        ///GROUP BY CLIENTS.ID.
        /// </summary>
        internal static string BookCounter {
            get {
                return ResourceManager.GetString("BookCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Books {
            get {
                object obj = ResourceManager.GetObject("Books", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Booktypes {
            get {
                object obj = ResourceManager.GetObject("Booktypes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clients {
            get {
                object obj = ResourceManager.GetObject("Clients", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Librarian {
            get {
                object obj = ResourceManager.GetObject("Librarian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT MAX(FULLFINE)
        ///FROM (
        ///    SELECT CLIENT_ID,SUM(FINE*DAYS) as fullfine
        ///    FROM (
        ///        SELECT 
        ///            JOURNAL.CLIENT_ID,BOOK_TYPES.FINE,ROUND((MONTHS_BETWEEN(JOURNAL.DATE_RET,JOURNAL.DATE_END)/12)*365) days
        ///        FROM JOURNAL
        ///        INNER JOIN BOOKS
        ///            ON JOURNAL.BOOK_ID = BOOKS.ID
        ///        INNER JOIN BOOK_TYPES
        ///            ON BOOKS.TYPE_ID = BOOK_TYPES.ID
        ///    )
        ///    GROUP BY CLIENT_ID
        ///).
        /// </summary>
        internal static string MaxFine {
            get {
                return ResourceManager.GetString("MaxFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT FULLFINE
        ///FROM (
        ///    SELECT CLIENT_ID,SUM(FINE*DAYS) as fullfine
        ///    FROM (
        ///        SELECT 
        ///            JOURNAL.CLIENT_ID,JOURNAL.BOOK_ID,BOOKS.TYPE_ID,BOOK_TYPES.FINE,ROUND((MONTHS_BETWEEN(JOURNAL.DATE_RET,JOURNAL.DATE_END)/12)*365) days
        ///        FROM JOURNAL
        ///        INNER JOIN BOOKS
        ///            ON JOURNAL.BOOK_ID = BOOKS.ID
        ///        INNER JOIN BOOK_TYPES
        ///            ON BOOKS.TYPE_ID = BOOK_TYPES.ID
        ///    )
        ///    GROUP BY CLIENT_ID
        ///    ORDER BY CLIENT_ID
        ///)
        ///WHERE  FULLFINE &gt; 0 and CLIENT_ID = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpecificFine {
            get {
                return ResourceManager.GetString("SpecificFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM (
        ///
        ///    SELECT JOURNAL.BOOK_ID, BOOKS.NAME, COUNT(*) as cnt 
        ///    FROM JOURNAL
        ///    INNER JOIN BOOKS
        ///        ON JOURNAL.BOOK_ID = BOOKS.ID
        ///    GROUP BY JOURNAL.BOOK_ID,BOOKS.NAME
        ///    ORDER BY cnt DESC
        ///)WHERE ROWNUM &lt;= 3.
        /// </summary>
        internal static string Top3 {
            get {
                return ResourceManager.GetString("Top3", resourceCulture);
            }
        }
    }
}
