SELECT MAX("MAX FINE") FROM
(
SELECT CLIENTS.FIRST_NAME, CLIENTS.LAST_NAME, CLIENTS.FATHER_NAME, MAX(TOTAL_FINES.FINE_SUM) AS "MAX FINE"
  FROM (
    SELECT JOURNAL.CLIENT_ID AS FINEMAN_ID, SUM(DECODE(SIGN(EXTRACT(DAY FROM((JOURNAL.DATE_RET - JOURNAL.DATE_END)))),1,(BOOK_TYPES.FINE * EXTRACT(DAY FROM((JOURNAL.DATE_RET - JOURNAL.DATE_END)))),-1,0,0)) AS FINE_SUM
      FROM JOURNAL
      INNER JOIN BOOKS ON JOURNAL.BOOK_ID = BOOKS.ID
      INNER JOIN BOOK_TYPES ON BOOKS.TYPE_ID = BOOK_TYPES.ID
      GROUP BY JOURNAL.CLIENT_ID) TOTAL_FINES
  INNER JOIN CLIENTS ON TOTAL_FINES.FINEMAN_ID = CLIENTS.ID
  GROUP BY CLIENTS.FIRST_NAME, CLIENTS.LAST_NAME, CLIENTS.FATHER_NAME
  ORDER BY MAX(TOTAL_FINES.FINE_SUM) DESC
)