SELECT FULLFINE
FROM (
    SELECT CLIENT_ID,SUM(FINE*DAYS) as fullfine
    FROM (
        SELECT 
            JOURNAL.CLIENT_ID,JOURNAL.BOOK_ID,BOOKS.TYPE_ID,BOOK_TYPES.FINE,ROUND((MONTHS_BETWEEN(JOURNAL.DATE_RET,JOURNAL.DATE_END)/12)*365) days
        FROM JOURNAL
        INNER JOIN BOOKS
            ON JOURNAL.BOOK_ID = BOOKS.ID
        INNER JOIN BOOK_TYPES
            ON BOOKS.TYPE_ID = BOOK_TYPES.ID
    )
    GROUP BY CLIENT_ID
    ORDER BY CLIENT_ID
)
WHERE  fullfine > 0 AND CLIENT_ID = :CLIENT_ID