SELECT *
FROM (

    SELECT JOURNAL.BOOK_ID, BOOKS.NAME, COUNT(*) as cnt 
    FROM JOURNAL
    INNER JOIN BOOKS
        ON JOURNAL.BOOK_ID = BOOKS.ID
    GROUP BY JOURNAL.BOOK_ID,BOOKS.NAME
    ORDER BY cnt DESC
)WHERE ROWNUM <= 3